import { Platform } from 'react-native';
import { useMutation } from '@tanstack/react-query';
import { Directory, File, FileMode, Paths, UploadType } from 'expo-file-system';
import { ApiError } from './api-client';
import { getItem } from './storage';
import { API_V1_URL, TOKEN_KEYS } from '../constants/config';
import { useBranch } from './branch';
import type { ParseResult } from './file-receiving-rules';

export * from './file-receiving-rules';

/**
 * Sending the shop's file to the server.
 *
 * ## Why this is not one `fetch`
 *
 * On a phone the file does not belong to the app. The document picker hands
 * back a uri owned by Files, iCloud Drive, WhatsApp or another app, readable
 * only for as long as iOS says so. React Native's own multipart part is built
 * from that uri inside the networking layer, so when the uri is no longer
 * readable the request fails there — with no status, no response, and a message
 * indistinguishable from the shop's Wi-Fi being down.
 *
 * That is exactly what happened on the first device attempt: everything else on
 * the phone was talking to the server, and only this upload reported itself as
 * offline.
 *
 * So the file is copied into the app's own cache first and checked there —
 * it exists, it has bytes, the byte count matches what the picker declared, a
 * workbook starts with a ZIP signature — and the upload is then handed to
 * Expo's native uploader from that verified copy. Nothing about the request is
 * assembled in JavaScript: same URL, same authorisation and branch headers as
 * every other call, multipart field `file`, and the boundary generated by the
 * platform rather than set by us.
 */

// ── stages, so a failure says where it stopped ──────────────────────────────

export type UploadStage = 'picked' | 'copied' | 'verified' | 'started' | 'answered';

/** Development-only, and metadata only: never the file's contents. */
function stage(name: UploadStage, detail: Record<string, unknown>) {
  if (__DEV__) console.log(`[receive/file] ${name}`, detail);
}

const CACHE_FOLDER = 'receiving-files';

/** A name the file system will accept, still ending in the original extension. */
function safeName(name: string): string {
  const cleaned = name.replace(/[^\w.\-]+/g, '_');
  return cleaned.length > 0 ? cleaned : 'delivery.xlsx';
}

function cacheDir(): Directory {
  const dir = new Directory(Paths.cache, CACHE_FOLDER);
  if (!dir.exists) dir.create({ intermediates: true });
  return dir;
}

/** The first bytes, read without pulling the whole workbook into memory. */
function head(file: File, length: number): Uint8Array | null {
  try {
    const handle = file.open(FileMode.ReadOnly);
    try {
      return handle.readBytes(length);
    } finally {
      handle.close();
    }
  } catch {
    return null;
  }
}

const ZIP_SIGNATURE = [0x50, 0x4b, 0x03, 0x04];

export interface PickedFile {
  uri: string;
  name: string;
  mimeType?: string;
  /** What the picker said the file weighs, when it said anything. */
  size?: number;
  /** The picker hands web a real File; a phone hands us a uri. */
  file?: unknown;
}

/**
 * Copy the picked file into the app's cache and satisfy ourselves it is there.
 *
 * Returns the cached copy. Throws with a code naming what was wrong, never a
 * bare failure: "the file is gone" and "the file is empty" are different things
 * to tell a shopkeeper, and neither is "the server is down".
 */
async function cacheCopy(input: PickedFile): Promise<File> {
  const name = safeName(input.name);
  const destination = new File(cacheDir(), name);

  try {
    const source = new File(input.uri);
    if (destination.exists) destination.delete();
    await source.copy(destination);
  } catch (e) {
    // The picker's own copy may already be gone. If we cached this file on an
    // earlier attempt, that copy is still good — a retry must not need the
    // document provider again.
    if (destination.exists && (destination.size ?? 0) > 0) {
      stage('copied', { reused: true, size: destination.size });
      return destination;
    }
    stage('copied', { failed: true, message: e instanceof Error ? e.message : 'unknown' });
    throw new ApiError('The chosen file could not be opened', 0, 'file_gone', null);
  }
  stage('copied', { size: destination.size, name });
  return destination;
}

function verify(file: File, input: PickedFile): { size: number; mimeType: string } {
  if (!file.exists) throw new ApiError('The chosen file is no longer there', 0, 'file_gone', null);

  const size = file.size ?? 0;
  if (size === 0) throw new ApiError('The chosen file is empty', 0, 'file_empty_local', null);

  if (typeof input.size === 'number' && input.size > 0 && input.size !== size) {
    stage('verified', { mismatch: true, declared: input.size, copied: size });
    throw new ApiError('The copy is not the file that was chosen', 0, 'file_gone', null);
  }

  const looksLikeWorkbook = /\.xlsx$/i.test(input.name);
  if (looksLikeWorkbook) {
    const first = head(file, 4);
    const ok = first !== null && ZIP_SIGNATURE.every((b, i) => first[i] === b);
    if (!ok) {
      stage('verified', { signature: first ? [...first].map((b) => b.toString(16)) : null });
      throw new ApiError('That workbook could not be opened', 0, 'file_unreadable', null);
    }
  }

  const mimeType =
    input.mimeType && input.mimeType !== 'application/octet-stream'
      ? input.mimeType
      : looksLikeWorkbook
        ? 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        : /\.pdf$/i.test(input.name)
          ? 'application/pdf'
          : (input.mimeType ?? 'application/octet-stream');

  stage('verified', { size, mimeType, name: input.name });
  return { size, mimeType };
}

/** Is the server actually reachable? Asked only to tell "offline" from "the upload would not start". */
async function serverAnswers(token: string | null): Promise<boolean> {
  try {
    const res = await fetch(`${API_V1_URL}/auth/me`, {
      headers: token ? { authorization: `Bearer ${token}` } : {},
    });
    return res.status > 0;
  } catch {
    return false;
  }
}

function answer(status: number, body: string): ParseResult {
  let parsed: (ParseResult & { message?: string; code?: string }) | null = null;
  try {
    parsed = JSON.parse(body);
  } catch {
    parsed = null;
  }
  stage('answered', { status, code: parsed?.code ?? null });
  if (status < 200 || status >= 300) {
    throw new ApiError(parsed?.message ?? 'Could not read that file', status, parsed?.code, parsed);
  }
  return parsed as ParseResult;
}

export function useParseReceivingFile() {
  const branchId = useBranch((s) => s.branchId);
  return useMutation({
    mutationFn: async (input: PickedFile & { sheet?: string; mapping?: Record<string, number> }) => {
      const token = await getItem(TOKEN_KEYS.ACCESS_TOKEN);
      const url = `${API_V1_URL}/purchases/file/parse`;
      const headers = {
        ...(token ? { authorization: `Bearer ${token}` } : {}),
        ...(branchId ? { 'x-branch-id': branchId } : {}),
      };
      const parameters = {
        ...(input.sheet ? { sheet: input.sheet } : {}),
        ...(input.mapping ? { mapping: JSON.stringify(input.mapping) } : {}),
      };
      stage('picked', {
        url,
        name: input.name,
        mimeType: input.mimeType,
        declaredSize: input.size,
        scheme: input.uri.split(':')[0],
        branch: Boolean(branchId),
        authenticated: Boolean(token),
      });

      // Web: the picker already handed us the file itself, and there is no
      // native uploader to hand it to.
      if (Platform.OS === 'web' || input.file) {
        const form = new FormData();
        form.append('file', input.file as Blob, input.name);
        for (const [key, value] of Object.entries(parameters)) form.append(key, value);
        // No content type of our own, or the generated boundary is lost.
        const res = await fetch(url, { method: 'POST', headers, body: form });
        return answer(res.status, await res.text());
      }

      const cached = await cacheCopy(input);
      const { mimeType } = verify(cached, input);

      stage('started', { url, fieldName: 'file' });
      let result;
      try {
        result = await cached.upload(url, {
          httpMethod: 'POST',
          uploadType: UploadType.MULTIPART,
          fieldName: 'file',
          mimeType,
          headers,
          parameters,
        });
      } catch (e) {
        // Nothing came back. Tell a refused upload from a server that is not
        // there, because on this phone everything else was reaching the server
        // perfectly well.
        const reachable = await serverAnswers(token);
        stage('started', { failed: true, reachable, message: e instanceof Error ? e.message : 'unknown' });
        throw reachable
          ? new ApiError('The upload could not be started', 0, 'upload_failed', null)
          : new ApiError('The server could not be reached', 0, 'offline', null);
      }
      return answer(result.status, result.body);
    },
  });
}
