/**
 * Creating a shop's account, on the phone (milestone P).
 *
 * Account creation used to open a browser at the website. That is retired: a
 * shop is set up by scanning stock, scanning happens on the phone, and sending
 * somebody to a browser to type their details meant using the surface with the
 * worst keyboard for the longest form in the product — then doing the real work
 * somewhere else.
 *
 * ## What this file is
 *
 * The rules, with no React and no network, so they can be tested directly. The
 * screen renders these decisions; it does not make them.
 *
 * ## What it deliberately does not collect
 *
 * No Store ID, company id, branch id, national or personal ID, role, permission
 * or subscription identifier. Every internal reference is generated by the
 * server. Asking somebody to invent or remember our identifiers is exactly how
 * the old sign-in became unusable — the type below is the guard: there is no
 * field to put one in.
 */

import type { Language } from './i18n';

export interface RegistrationDraft {
  ownerName: string;
  businessName: string;
  branchName: string;
  city: string;
  email: string;
  /** WhatsApp number. Either this or `email` is enough; both is fine. */
  phone: string;
  password: string;
  passwordConfirm: string;
}

export const emptyRegistration: RegistrationDraft = {
  ownerName: '',
  businessName: '',
  branchName: '',
  city: '',
  email: '',
  phone: '',
  password: '',
  passwordConfirm: '',
};

/** Which field a problem belongs to, so it can be shown beside its input. */
export type RegistrationField =
  | 'ownerName'
  | 'businessName'
  | 'branchName'
  | 'contact'
  | 'email'
  | 'phone'
  | 'password'
  | 'passwordConfirm';

/** A translation key, never a sentence — this module renders nothing. */
export type RegistrationProblems = Partial<Record<RegistrationField, string>>;

/** Mirrors the server's `MinLength(8)`. Kept here only to fail fast, not to decide. */
export const MIN_PASSWORD = 8;

const EMAIL = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
/** Digits, optionally an international +. The server normalises properly. */
const PHONE = /^\+?[\d\s-]{6,24}$/;

/**
 * What is wrong with this draft, if anything.
 *
 * Returns keys rather than text so the same rules hold in all three languages,
 * and so a test can assert on a rule instead of on a sentence somebody may
 * reword later.
 */
export function validateRegistration(draft: RegistrationDraft): RegistrationProblems {
  const problems: RegistrationProblems = {};

  if (!draft.ownerName.trim()) problems.ownerName = 'register.problem.ownerName';
  if (!draft.businessName.trim()) problems.businessName = 'register.problem.businessName';
  if (!draft.branchName.trim()) problems.branchName = 'register.problem.branchName';

  const email = draft.email.trim();
  const phone = draft.phone.trim();

  // At least one contact, because it IS the credential — an account with
  // neither cannot reach the sign-in screen at all. The server refuses this
  // too; catching it here saves a round trip, it does not replace the rule.
  if (!email && !phone) {
    problems.contact = 'register.problem.contact';
  }
  if (email && !EMAIL.test(email)) problems.email = 'register.problem.email';
  if (phone && !PHONE.test(phone)) problems.phone = 'register.problem.phone';

  if (draft.password.length < MIN_PASSWORD) problems.password = 'register.problem.password';
  // Checked even when the password is too short: somebody fixing one error
  // should see both, not discover the second after fixing the first.
  if (draft.passwordConfirm !== draft.password) {
    problems.passwordConfirm = 'register.problem.passwordConfirm';
  }

  return problems;
}

export function isRegistrationValid(draft: RegistrationDraft): boolean {
  return Object.keys(validateRegistration(draft)).length === 0;
}

/**
 * The contact a verification code is sent to.
 *
 * Email wins when both are given: it is the one somebody can read on the device
 * they are already holding, and WhatsApp delivery is not wired up yet.
 */
export function verificationTarget(draft: RegistrationDraft): string | null {
  return draft.email.trim() || draft.phone.trim() || null;
}

/** The exact body `POST /platform/register` expects. Optional fields are omitted, never empty. */
export function registrationPayload(
  draft: RegistrationDraft,
  idempotencyKey: string,
  language: Language,
): Record<string, string> {
  const body: Record<string, string> = {
    idempotencyKey,
    ownerName: draft.ownerName.trim(),
    businessName: draft.businessName.trim(),
    branchName: draft.branchName.trim(),
    password: draft.password,
    language,
  };
  if (draft.city.trim()) body.city = draft.city.trim();
  if (draft.email.trim()) body.email = draft.email.trim();
  if (draft.phone.trim()) body.phone = draft.phone.trim();
  return body;
}

/**
 * Everything the screen may keep after the account exists.
 *
 * The password is **not** in it. Holding the plaintext to "log the user in
 * afterwards" would mean keeping a credential in memory for the sake of
 * convenience; the server issues a session instead.
 */
export function draftWithoutSecret(draft: RegistrationDraft): Omit<
  RegistrationDraft,
  'password' | 'passwordConfirm'
> {
  const { password: _p, passwordConfirm: _c, ...rest } = draft;
  return rest;
}
