import React, { useRef, useState } from 'react';
import { KeyboardAvoidingView, Platform, ScrollView, StyleSheet, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Stack, useRouter } from 'expo-router';
import { AuthLanguageSwitch, Button, Field } from '../../components/ui';
import { Text } from '../../components/ui/Text';
import { api, ApiError } from '../../lib/api-client';
import { useTranslation } from '../../lib/i18n';
import { useColors } from '../../lib/design/theme';
import { space } from '../../lib/design/tokens';
import { uuidv4 } from '../../lib/utils';
import {
  emptyRegistration,
  registrationPayload,
  validateRegistration,
  type RegistrationDraft,
  type RegistrationProblems,
} from '../../lib/registration';
import { rememberContinuation } from '../../lib/registration-session';
import type { RegistrationStarted } from '../../types/api';

/**
 * Creating a shop's account, on the phone.
 *
 * This used to open a browser at the website. Setting a shop up means scanning
 * stock, scanning happens here, and sending somebody to a browser to type the
 * longest form in the product — on the surface with the worst keyboard — before
 * doing the real work somewhere else was never going to be the shorter path.
 *
 * ## What it never asks for
 *
 * No Store ID, company id, branch id, personal or national ID, role, permission
 * or subscription identifier. Every internal reference is generated by the
 * server. The draft type in `lib/registration.ts` has no field for one, so this
 * is structural rather than a habit.
 *
 * ## The idempotency key
 *
 * Generated **once**, when this screen mounts, and reused for every retry. A
 * dropped response on a bad connection is the ordinary case in a Nouakchott
 * shop; without a stable key the anxious second tap creates a second business
 * with the same name and no way to tell which one is yours.
 */
export default function RegisterScreen() {
  const { t } = useTranslation();
  const router = useRouter();
  const colors = useColors();

  const [draft, setDraft] = useState<RegistrationDraft>(emptyRegistration);
  const [problems, setProblems] = useState<RegistrationProblems>({});
  const [failure, setFailure] = useState<string | null>(null);
  const [submitting, setSubmitting] = useState(false);

  /** One identity for this attempt, however many times it is retried. */
  const idempotencyKey = useRef(uuidv4());
  /** Synchronous, because two taps can land before a render. */
  const inFlight = useRef(false);

  const set = <K extends keyof RegistrationDraft>(key: K, value: string) => {
    setDraft((d) => ({ ...d, [key]: value }));
    // Clear only the field being corrected: wiping every message would hide
    // problems the person has not looked at yet.
    setProblems((p) => ({ ...p, [key]: undefined, contact: undefined }));
    setFailure(null);
  };

  const submit = async () => {
    if (inFlight.current) return;

    const found = validateRegistration(draft);
    setProblems(found);
    if (Object.keys(found).length > 0) return;

    inFlight.current = true;
    setSubmitting(true);
    setFailure(null);
    try {
      const started = await api.post<RegistrationStarted>(
        '/platform/register',
        registrationPayload(draft, idempotencyKey.current, 'en'),
      );

      /*
       * The continuation goes to secure storage and nowhere else. It is not a
       * session and buys nothing on its own, but it is the credential that
       * finishes this registration, so it is treated like one.
       */
      if (started.continuation?.token) {
        await rememberContinuation(started.continuation.token);
      }

      /*
       * The password is not carried forward. Nothing keeps it to "log them in
       * afterwards" — the server issues a session when the contact is proved.
       */
      setDraft((d) => ({ ...d, password: '', passwordConfirm: '' }));

      router.replace({
        pathname: '/(auth)/verify',
        params: { destination: started.verification?.destination ?? '' },
      } as never);
    } catch (e) {
      // The server's own wording when it has some, because it knows things this
      // screen does not — a taken address, a rate limit.
      setFailure(e instanceof ApiError && e.message ? e.message : t('register.failed'));
    } finally {
      inFlight.current = false;
      setSubmitting(false);
    }
  };

  const problem = (key: keyof RegistrationProblems) =>
    problems[key] ? t(problems[key] as never) : undefined;

  return (
    <SafeAreaView style={[styles.fill, { backgroundColor: colors.surface.canvas }]}>
      <Stack.Screen options={{ headerShown: true, title: t('register.title') }} />
      <KeyboardAvoidingView
        style={styles.fill}
        behavior={Platform.OS === 'ios' ? 'padding' : undefined}
      >
        <ScrollView
          contentContainerStyle={styles.content}
          keyboardShouldPersistTaps="handled"
          keyboardDismissMode="on-drag"
        >
          <Text variant="body" tone="secondary">
            {t('register.subtitle')}
          </Text>

          <View style={styles.group}>
            <Text variant="label">{t('register.section.business')}</Text>
            <Field
              label={t('register.field.businessName')}
              hint={t('register.field.businessName.hint')}
              value={draft.businessName}
              onChangeText={(v) => set('businessName', v)}
              autoCapitalize="words"
              error={problem('businessName')}
            />
            <Field
              label={t('register.field.branchName')}
              hint={t('register.field.branchName.hint')}
              value={draft.branchName}
              onChangeText={(v) => set('branchName', v)}
              autoCapitalize="words"
              error={problem('branchName')}
            />
            <Field
              label={t('register.field.city')}
              value={draft.city}
              onChangeText={(v) => set('city', v)}
              autoCapitalize="words"
            />
          </View>

          <View style={styles.group}>
            <Text variant="label">{t('register.section.owner')}</Text>
            <Field
              label={t('register.field.ownerName')}
              value={draft.ownerName}
              onChangeText={(v) => set('ownerName', v)}
              autoCapitalize="words"
              autoComplete="name"
              error={problem('ownerName')}
            />
          </View>

          <View style={styles.group}>
            <Text variant="label">{t('register.section.contact')}</Text>
            <Text variant="caption" tone="secondary">
              {t('register.contact.hint')}
            </Text>
            <Field
              label={t('register.field.email')}
              value={draft.email}
              onChangeText={(v) => set('email', v)}
              keyboardType="email-address"
              autoCapitalize="none"
              autoComplete="email"
              error={problem('email')}
            />
            <Field
              label={t('register.field.phone')}
              value={draft.phone}
              onChangeText={(v) => set('phone', v)}
              keyboardType="phone-pad"
              autoComplete="tel"
              error={problem('phone')}
            />
            {problems.contact ? (
              <Text variant="caption" tone="danger">
                {t('register.problem.contact')}
              </Text>
            ) : null}
          </View>

          <View style={styles.group}>
            <Text variant="label">{t('register.section.password')}</Text>
            <Field
              label={t('register.field.password')}
              hint={t('register.field.password.hint')}
              value={draft.password}
              onChangeText={(v) => set('password', v)}
              secureTextEntry
              autoCapitalize="none"
              autoComplete="new-password"
              error={problem('password')}
            />
            <Field
              label={t('register.field.passwordConfirm')}
              value={draft.passwordConfirm}
              onChangeText={(v) => set('passwordConfirm', v)}
              secureTextEntry
              autoCapitalize="none"
              autoComplete="new-password"
              error={problem('passwordConfirm')}
            />
          </View>

          {failure ? (
            <Text variant="body" tone="danger" align="center">
              {failure}
            </Text>
          ) : null}

          <View style={styles.group}>
            <Button
              title={submitting ? t('register.creating') : t('register.submit')}
              onPress={() => void submit()}
              loading={submitting}
              disabled={submitting}
            />
            <Button
              title={t('register.back')}
              variant="secondary"
              onPress={() => router.back()}
              disabled={submitting}
            />

            {/*
              The longest form in the product, and the one most likely to be
              filled in by somebody who was handed the phone. Changing the
              language here keeps every field exactly as typed: this writes a
              preference and re-renders, it does not remount the form.
            */}
            <AuthLanguageSwitch />
          </View>
        </ScrollView>
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  fill: { flex: 1 },
  content: { padding: space.lg, gap: space.lg },
  group: { gap: space.md },
});
